---
name: Security Scan
on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  push:
    branches:
      - main

jobs:
  container-scanning:
    name: Container - Vulnerability Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Export to Docker
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          load: true
          tags: security-scan-target

      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: security-scan-target
          ignore-unfixed: true
          format: sarif
          output: trivy-results.sarif

      - name: Upload Scan Results to GitHub Security Tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif